### ISSUE TITLE
help in using the lib.

### ISSUE THREAD

**Issue by rahmanshaber** [marcusbritanicus/libarchive-qt#4]
i tried this . as usual nothing.

`   QString h( "/home/shaber/Desktop/test" );
LibArchive *arc = new LibArchive(h);
    arc->updateInputFiles( h);
    arc->create();
`

how i do this properly?

**Comment by marcusbritanicus** [comment]
The problem is with `LibArchive(h)`. `h` is your input file right? What is your output file? It cannot be `h`.

Secondly, `Libarchive::updateInputFiles( ... )` expects a list of `QString`s as its argument. So you cannot just put `h` for everything. The program should be:

    QStringList infiles = QStringList() << QString( "/home/shaber/Desktop/test" );
    LibArchive *arc = new LibArchive( "/home/shaber/Desktop/test.zip" );
    arc->updateInputFiles( infiles );
    arc->create();
