### ISSUE TITLE
update the library 

### ISSUE THREAD

**Issue by rahmanshaber** [marcusbritanicus/libarchive-qt#5]
I saw your using new function and archive option in NewBreeze file manager.
Could you please consider to add those function and feature to this library.

thanks.

**Comment by marcusbritanicus** [comment]
Its already in place. I took the code from here and put it there. Go through the example code. It has how to use it. 

PS: 
I hope you know that I'm shifting from github to GitLab. No more new code will be added here. All further development will take place in [GitLab](https://gitlab.com/users/marcusbritanicus/projects). Some more updates have been pushed to NewBreeze on GitLab.
